import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { footerNavItems } from "./data/footer";
import "./globals.css";

export const metadata = {
  title: "ICGC ARGO Docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar
          navItems={undefined}
          logo={undefined}
          Menu={undefined}
          Search={undefined}
        />
        {children}
        <Footer navItems={footerNavItems} copyright={"Copyright?"} />
      </body>
    </html>
  );
}
