// ****************************************************************************************
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Autogenerated file from https://github.com/icgc-argo/argo-docs/scripts/links/generate.js
// Do not modify; change only comes from within.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// ****************************************************************************************

import urljoin from 'url-join';
import { getConfig } from 'global/config';

const { DOCS_URL_ROOT } = getConfig();

export const DOCS_DICTIONARY_PATH = '/dictionary/';
